[package]
name = "monkey-web"
version = "0.0.0"
authors = ["Joe Corcoran <joe@corcoran.online>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
js-sys = "0.3"
monkey-core = { path = "../monkey-core" }

[profile.release]
lto = true
